### ISSUE TITLE
Warmup won’t load at startup

### ISSUE THREAD

**Issue by brightspark1968** [ha-warmup/warmup#27] opened 2021-04-25 09:45 UTC
No 'version' key in the manifest file for custom integration 'warmup'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'warmup'

I am by no means an expert but making sure this is noted. My integration no longer loads.

**Comment by rct** [comment] 2021-05-21 16:05
Is this a duplicate of #25?

If I understand things correctly, for HASS versions up to 2021.5.x, there should just be a warning, warmup shouldn't fail to load.  

Starting with the next release, warmup **should fail to load** if the manifest issue isn't resolved.

**Closed** 2021-06-03 14:53 UTC
