### ISSUE TITLE
Use of Depreciated Constants

### ISSUE THREAD

**Issue by oceanice** [ha-warmup/warmup#65] opened 2024-01-05 20:02 UTC
After upgrading to Home Assistant 2024.0 I am receiving the following warning in my files.

Hopefully this can be fixed

thanks for this great plugin

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:205
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 19:46:32 (8 occurrences)
Last logged: 19:46:32

HVAC_MODE_AUTO was used from warmup, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please create a bug report at https://github.com/ha-warmup/warmup/issues/
HVAC_MODE_HEAT was used from warmup, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/ha-warmup/warmup/issues/
HVAC_MODE_OFF was used from warmup, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/ha-warmup/warmup/issues/
SUPPORT_PRESET_MODE was used from warmup, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/ha-warmup/warmup/issues/
SUPPORT_TARGET_TEMPERATURE was used from warmup, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/ha-warmup/warmup/issues/

**Comment by artmg** [comment] 2024-01-05 21:34
Thank you very much for notifying us of this deprecation warning, @oceanice

Fortunately the HA Core team is giving us sufficient time to get this resolved before it risks failure. The code change looks like it should be relatively simple to switch over, but it will be handy if people are available to test once the changes are developed.

I, or one of the other devs, will announce when a PR is ready with a new branch of this plugin. Then hopefully we can get instructions issued for those who install manually AND those who install via HACS, to get thorough testing before a formal release.

In the meantime, I hope that you continue to enjoy your warmth-coming-up in that time of year when it's needed the most :)

**Comment by robchandhok** [comment] 2024-01-12 17:25
I'm already working on it, not done yet.

**Comment by robchandhok** [comment] 2024-01-12 18:10
I've tested a fixed version of climate.py, off master.  @artmg I can do a PR if you like, or if you prefer I can re-do on the new branch.

**Comment by artmg** [comment] 2024-01-12 22:11
Thanks for getting onto that so quickly, @robchandhok - your fix-2024-constants branch looks fine to PR upstream. And yes, I need to clean up `dev` up here.

Would you mind just doing the [compare to the new branch](https://github.com/ha-warmup/warmup/compare/depr_25.1_hvac...robchandhok:warmup:fix-2024-constants) to raise the PR, so that people can elect to test it before we bring it into the master and publish it towards HACS. 

I appreciate your prompt code contribution!

**Comment by artmg** [comment] 2024-01-13 13:31
Thanks to Rob, the modified code is now available for testing, first via the branch `depr_25.1_hvac`. Anyone who wishes to test may use the [alternative manual install method](https://github.com/ha-warmup/warmup?tab=readme-ov-file#alternative-versions) specifying this branch, e.g. 

```
git clone -b depr_25.1_hvac https://github.com/ha-warmup/warmup.git /tmp/warmup
```

Once we have an independent thumbs up or two I will [bundle this up as a beta release](https://github.com/ha-warmup/warmup/blob/master/CONTRIBUTING.md#release) for HACS users to test.

**Comment by peternash** [comment] 2024-01-30 10:16
I was able to install the depr_25.1_hvac branch on HASOS / HACS by calling the update.install service
`
service: update.install
data:
  version: depr_25.1_hvac
target:
  entity_id: update.warmup_under_floor_heating_integration_update
`
Warmup 6iE, single zone electric underfloor heating.  All looks OK so far and I can confirm the deprecation warnings are gone.

**Comment by artmg** [comment] 2024-02-07 14:10
This has now been set as [Prerelease v2024.2.7](https://github.com/ha-warmup/warmup/releases/tag/v2024.2.7) so should be available to all HACS users who have set [show beta versions](https://github.com/ha-warmup/warmup/blob/v2024.2.7/CONTRIBUTING.md#beta) on their HACS Warmup component. 

Please report any remaining issues else I will close this issue soon. 

Thanks to all who helped identify, develop and test this issue!

**Comment by robchandhok** [comment] 2024-02-18 22:50
@artmg I think this should get pushed to a real (non-beta) release and closed.  thanks!

**Comment by artmg** [comment] 2024-02-24 14:35
Release unmarked as Prerelease and Marked as Latest. Thanks for you commits and support @robchandhok and for your reporting @oceanice and @peternash

**Closed by artmg** 2024-02-24 14:35 UTC
Labels: good first issue, deprecation
